### ISSUE TITLE
Workshop content outside of the home folder is not found

### ISSUE THREAD

**Issue by DanMan** [ValveSoftware/steam-runtime#257]
#### Your system information

* Steam Runtime Version: 0.20200417.0
* Distribution: Ubuntu 18.04.4 LTS (64 bit) 
* Link to your full system information:  https://gist.github.com/DanMan/df94fe2dc319aad76fc097c2f90e6329
* Have you checked for system updates?: [Yes]
* Are you using the Steam Linux Runtime compatibility tool?: [Yes]

#### Please describe your issue in as much detail as possible:

XCOM 2 launches, but if you're using mods from the Workshop and try to load a savegame, it warns you that it can't find the mods that are required for that savegame. Same happens when Steam is in offline mode btw.

#### Steps for reproducing this issue:

1. Launch game with runtime active
2. try to load a savegame that depends on mods and was created when the runtime wasn't active

**Comment by smcv** [comment]
Are the mods and the game stored in different Steam library directories?

**Comment by DanMan** [comment]
> Are the mods and the game stored in different Steam library directories?

No, they're in the same library as the game itself.

**Comment by smcv** [comment]
That makes sense. Similar to #217, pressure-vessel can't get this right until Steam gives it more information about which directories ought to be shared with the container.

The same will be likely true for any game that has Workshop support and is installed outside your home directory. @kisak-valve, please could you retitle this more generically?

**Comment by smcv** [comment]
This is hopefully fixed in a newer pressure-vessel version. Please try with the "Steam Linux Runtime" set to the public beta branch `client_beta`, and the latest Steam client beta (Sep 10 2020 or newer). `SteamLinuxRuntime/VERSIONS.txt` should identify it as pressure-vessel 0.20200909.0+srt1 and scout 0.20200910.0.

Note that the beta Steam Linux Runtime is not expected to work with Steam client versions older than the current beta. This is not considered to be a bug.

**Comment by DanMan** [comment]
Did that, but XCOM2 didn't want to load my old savegames, complained that some mods were missing still.

VERSIONS.txt
``` 
#Name	Version	Comment
SteamLinuxRuntime	v0-103-gbbbff78	# Entry point scripts, etc.
pressure-vessel	0.20200909.0+srt1	# from scout version 0.20200910.0
scout	0.20200910.0	# com.valvesoftware.SteamRuntime.Platform-amd64,i386-scout-runtime.tar.gz
```

**Comment by RyuzakiKK** [comment]
I don't have XCOM 2, but I tested Team Fortress 2, installed outside my home directory, and the workshop items that I previously downloaded worked from the Steam Linux Runtime container.

@DanMan can you confirm if XCOM 2 still shows this issue?

**Comment by DanMan** [comment]
XCOM 2 now loaded my savegame without complaints.

```
#Name                           Version                                     Runtime                         Runtime_Version Comment
SteamLinuxRuntime       v0.20210114.1-2-g2bd4ab9                                            # Entry point scripts, etc.
pressure-vessel              0.20210203.0+srt1                    scout   0.20210217.0    # pressure-vessel-bin.tar.gz
scout                               0.20210217.0                            scout   0.20210217.0    # com.valvesoftware.SteamRuntime.Platform-amd64,i386-scout-runtime.tar.gz
```

**Comment by kisak-valve** [comment]
Thanks for retesting @DanMan, closing.
