### ISSUE TITLE
Soldier runtime: failure loading system-wide Proton versions

### ISSUE THREAD

**Issue by 414n** [ValveSoftware/steam-runtime#302]
#### Your system information

* Steam Runtime Version: soldier_0.20201022.1
* Distribution (e.g. Ubuntu 18.04): Slackware64-14.2
* Link to your full system information (Help -> System Information): [system_info](https://gist.github.com/414n/34891616266f2d4e4489173e8bbee632)
* Have you checked for system updates?: Yes
* Are you using the Steam Linux Runtime compatibility tool?: Yes

#### Please describe your issue in as much detail as possible:

After installing the latest Proton-5.21-GE-1 system-wide under `/usr/share/steam/compatibilitytools.d/`, I discovered that any game set to use it on Steam would fail with this error:

```
pressure-vessel-adverb[17685]: Failed to execute child process "/usr/share/steam/compatibilitytools.d/Proton-5.21-GE-1/proton" (No such file or directory)
```
Removing the system-wide install and extracting that same Proton version under `~/.steam/root/compatibilitytools.d` solved the issue.

I guess the new container runtime assumes that the Proton version to use is under ~/steam/root and does not map/mount system-wide Proton installations, that could be under `$STEAM_EXTRA_COMPAT_TOOLS_PATHS`, `/usr/share/steam/compatibilitytools.d/` or `/usr/local/share/steam/compatibilitytools.d/` (see ValveSoftware/steam-for-linux#6310).

#### Steps for reproducing this issue:

1. install a Proton version system wide, e.g. under `/usr/share/steam/compatibilitytools.d/`
2. restart Steam and choose that specific Proton version to run a game that would otherwise run with the new runtime and that Proton version
3. game won't start anymore

**Comment by smcv** [comment]
> I guess the new container runtime assumes that the Proton version to use is under ~/steam/root and does not map/mount system-wide Proton installations

Not quite, but close. It assumes the Proton version to use is either under `~/.steam/root`, `~/.steam/steam` (which can be different in rare cases), or one of your configured Steam libraries.

**Comment by smcv** [comment]
All the paths that are not under `/usr` should be reasonably straightforward to fix. Paths below `/usr` are more of a problem, because the runtime system reserves `/usr` for the runtime itself.

Workaround: please try appending `/run/host/usr/share/steam/compatibilitytools.d:/run/host/usr/local/share/steam/compatibilitytools.d` to `STEAM_EXTRA_COMPAT_TOOLS_PATHS`, and running Steam with that environment variable set.

(Editing that environment variable automatically is one of the possible longer-term solutions for this.)

**Comment by 414n** [comment]
Good idea, but I think it does not work unfortunately: [steam.log.gz](https://github.com/ValveSoftware/steam-runtime/files/5569653/steam.log.gz). The error seems to be the same.
Please tell me if you need more verbose logs.
BTW, is there some documentation about how the runtime and Proton interact with each other? I'd like to better understand how it all works.

**Comment by smcv** [comment]
I can see from your log why this is failing. We'll likely need more intrusive changes to fix this, then.

**Comment by 414n** [comment]
Is it the value set in `STEAM_COMPAT_TOOL_PATHS`?

**Comment by smcv** [comment]
No, I think the problem is that Steam uses the absolute path to the compat tool when it is building the command to run inside the container, under the assumption that the path will still be valid inside the container. That's going to be true for every path *except* paths below `/usr`.

**Comment by TTimo** [comment]
soldier 0.20201124.0 improves sharing of `STEAM_EXTRA_COMPAT_TOOLS_PATH` with the container. See https://steamcommunity.com/app/221410/discussions/2/2962768718547168164/ for details.

**Comment by 414n** [comment]
Thanks for the news, TTimo.
Have just tried the new runtime version, but it doesn't seem to change anything WRT this issue, as I still get the same error.
I launched steam with `STEAM_EXTRA_COMPAT_TOOLS_PATHS=/run/host/usr/share/steam/compatibilitytools.d:/run/host/usr/local/share/steam/compatibilitytools.d`.

[steam.log.gz](https://github.com/ValveSoftware/steam-runtime/files/5599495/steam.log.gz)

**Comment by smcv** [comment]
The new runtime version only partially fixes this. Compatibility tools from /usr/local/share and /usr/share are still not available; only access to non-/usr paths in `STEAM_EXTRA_COMPAT_TOOLS_PATHS` was fixed. A future runtime update should get /usr/local/share and /usr/share working too: we know approximately how to do it, but it wasn't working at release time and I didn't want to delay the next beta for this.

**Comment by 414n** [comment]
Ok, thanks for the explanation.
Will wait for an update to test again, then.

**Comment by smcv** [comment]
Here is a workaround that might work:

```
cd /path/to/SteamLinuxRuntime_soldier
mkdir -p soldier/files/share/steam
mkdir -p soldier/files/local/share/steam
ln -fns /run/host/usr/share/steam/compatibilitytools.d soldier/files/share/steam/
ln -fns /run/host/usr/local/share/steam/compatibilitytools.d soldier/files/local/share/steam/
```

Then use Steam as usual, without any special modifications to `STEAM_EXTRA_COMPAT_TOOLS_PATHS`. I'm hoping that this will be enough to get compat tools in /usr/local/share and /usr/share to work.

Please let me know whether this succeeds: if it does, we can include the equivalent in the next soldier update.

**Comment by 414n** [comment]
Yep, it works! :+1: 
Here's the log, if needed: [steam.log.gz](https://github.com/ValveSoftware/steam-runtime/files/5604432/steam.log.gz).
Thanks!

**Comment by Strykar** [comment]
What's a workaround for Steam `API version v020 built Oct 28 2020 (23:35:02), package version 1603992987` which appears to be the latest version available on Arch (not opting for Steam Beta)?

Arch Steam/proton-ge install paths [gist](https://gist.github.com/Strykar/7cb20eabf4e86815edc325c1bf0965b7).

**Comment by 414n** [comment]
I don't know if the workaround from smcv is applicable to non-beta Proton version.
Have you tried creating the two directories and symlinks that he mentioned?

**Comment by Strykar** [comment]
> I don't know if the workaround from smcv is applicable to non-beta Proton version.
> Have you tried creating the two directories and symlinks that he mentioned?

If you see the install paths gist I linked above, there is no `SteamLinuxRuntime_soldier` directory.

**Comment by 414n** [comment]
The `SteamLinuxRuntime_soldier` runtime is normally installed through Steam itself inside the SteamApps dir, not with a system package that I know of.
If you don't see it listed under the "Tools" category inside your library, then I guess you're out of luck and can't use your system-wide custom Proton version outside of Steam Beta, for now.

**Comment by Strykar** [comment]
> The `SteamLinuxRuntime_soldier` runtime is normally installed through Steam itself inside the SteamApps dir, not with a system package that I know of.

Thanks, found it under `/home/user/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier`, sadly creating the two directories and symlinks does not fix the issue. The Warframe launcher still exits a few seconds after attempting to start it.

**Comment by smcv** [comment]
@Strykar If you are not willing to use beta versions, the workaround is to wait for this to be resolved in a non-beta version, or use the official build of Proton. Any workaround suggested by unknown people on Github is going to be less official and less supportable than using the beta!

> The Warframe launcher still exits a few seconds after attempting to start it

Sorry, this is not enough information to even know whether you are experiencing the same bug as this. We would need to see Steam's stderr output.

If you are getting the same error message as in the original bug report:

```
pressure-vessel-adverb[SOMETHING]: Failed to execute child process "/usr/share/steam/compatibilitytools.d/SOMETHING/proton" (No such file or directory)
```

then it's likely the same bug, for which a solution is in progress.

If not, you are probably experiencing a different bug which should be reported separately.

**Comment by smcv** [comment]
Information about the Steam client beta, from an official source: https://support.steampowered.com/kb_article.php?ref=7021-eiah-8669

SteamLinuxRuntime_soldier beta: it's the same as https://support.steampowered.com/kb_article.php?ref=9847-WHXC-7326 but instead of starting by selecting CS:GO in your library, you select "Steam Linux Runtime - Soldier".

**Comment by TheAquabat** [comment]
I don't know if it is the same bug I have proton GE installed on ~/.steam/root/compatibilitytools.d/ doesn't work. Also proton 5.13-2 doesn't work.

**Comment by TheAquabat** [comment]
I don't know if it is the same bug


[167051.298899] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167051.385814] pressure-vessel[554093]: segfault at 0 ip 0000000000000000 sp 00007ffd728fa858 error 14 in pressure-vessel-launch[400000+14000]
[167051.385819] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167051.576254] pressure-vessel[554105]: segfault at 0 ip 0000000000000000 sp 00007ffcd6851478 error 14 in pressure-vessel-launch[400000+14000]
[167051.576259] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167052.524844] pressure-vessel[554122]: segfault at 0 ip 0000000000000000 sp 00007ffc204d4818 error 14 in pressure-vessel-launch[400000+14000]
[167052.524849] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167067.789622] pressure-vessel[554179]: segfault at 0 ip 0000000000000000 sp 00007ffe084d5bc8 error 14 in pressure-vessel-launch[400000+14000]
[167067.789627] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167067.865546] pressure-vessel[554178]: segfault at 0 ip 0000000000000000 sp 00007ffeef145a48 error 14 in pressure-vessel-launch[400000+14000]
[167067.865550] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167068.813213] pressure-vessel[554559]: segfault at 0 ip 0000000000000000 sp 00007ffe88909b38 error 14 in pressure-vessel-launch[400000+14000]
[167068.813217] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167212.065018] pressure-vessel[555813]: segfault at 0 ip 0000000000000000 sp 00007ffc60da4438 error 14 in pressure-vessel-launch[400000+14000]
[167212.065022] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167212.140190] pressure-vessel[555812]: segfault at 0 ip 0000000000000000 sp 00007ffff21f9368 error 14 in pressure-vessel-launch[400000+14000]
[167212.140194] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167212.228496] pressure-vessel[556193]: segfault at 0 ip 0000000000000000 sp 00007ffe8021de38 error 14 in pressure-vessel-launch[400000+14000]
[167212.228500] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167212.475626] pressure-vessel[556209]: segfault at 0 ip 0000000000000000 sp 00007fff46850ee8 error 14 in pressure-vessel-launch[400000+14000]
[167212.475630] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167213.500771] pressure-vessel[556226]: segfault at 0 ip 0000000000000000 sp 00007ffd3aeafe58 error 14 in pressure-vessel-launch[400000+14000]
[167213.500775] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167424.639559] pressure-vessel[558622]: segfault at 0 ip 0000000000000000 sp 00007ffedad1ef48 error 14 in pressure-vessel-launch[400000+14000]
[167424.639565] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167424.714610] pressure-vessel[558623]: segfault at 0 ip 0000000000000000 sp 00007ffe379780b8 error 14 in pressure-vessel-launch[400000+14000]
[167424.714615] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167424.800596] pressure-vessel[558997]: segfault at 0 ip 0000000000000000 sp 00007fff24683178 error 14 in pressure-vessel-launch[400000+14000]
[167424.800601] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167425.030433] pressure-vessel[559013]: segfault at 0 ip 0000000000000000 sp 00007ffe6114f6c8 error 14 in pressure-vessel-launch[400000+14000]
[167425.030437] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167426.074244] pressure-vessel[559030]: segfault at 0 ip 0000000000000000 sp 00007fff3433a8c8 error 14 in pressure-vessel-launch[400000+14000]
[167426.074248] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167546.119923] pressure-vessel[560157]: segfault at 0 ip 0000000000000000 sp 00007fff712ff228 error 14 in pressure-vessel-launch[400000+14000]
[167546.119928] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167546.195750] pressure-vessel[560158]: segfault at 0 ip 0000000000000000 sp 00007fff0f8bb4e8 error 14 in pressure-vessel-launch[400000+14000]
[167546.195754] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167546.282054] pressure-vessel[560541]: segfault at 0 ip 0000000000000000 sp 00007ffefd080cf8 error 14 in pressure-vessel-launch[400000+14000]
[167546.282059] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167546.572275] pressure-vessel[560556]: segfault at 0 ip 0000000000000000 sp 00007ffed7f241f8 error 14 in pressure-vessel-launch[400000+14000]
[167546.572280] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167547.540086] pressure-vessel[560573]: segfault at 0 ip 0000000000000000 sp 00007fffe778c788 error 14 in pressure-vessel-launch[400000+14000]
[167547.540091] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167638.945008] wlp8s0: authenticate with d4:6e:0e:cd:a1:c6
[167638.959434] wlp8s0: send auth to d4:6e:0e:cd:a1:c6 (try 1/3)
[167639.006870] wlp8s0: authenticated
[167639.008559] wlp8s0: associate with d4:6e:0e:cd:a1:c6 (try 1/3)
[167639.033176] wlp8s0: RX AssocResp from d4:6e:0e:cd:a1:c6 (capab=0x431 status=0 aid=1)
[167639.033295] wlp8s0: associated
[167809.760123] pressure-vessel[561929]: segfault at 0 ip 0000000000000000 sp 00007fff26209028 error 14 in pressure-vessel-launch[400000+14000]
[167809.760127] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167809.834091] pressure-vessel[561928]: segfault at 0 ip 0000000000000000 sp 00007ffe30f541d8 error 14 in pressure-vessel-launch[400000+14000]
[167809.834095] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167809.908724] pressure-vessel[562601]: segfault at 0 ip 0000000000000000 sp 00007fffed5a5098 error 14 in pressure-vessel-launch[400000+14000]
[167809.908728] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167810.185830] pressure-vessel[562622]: segfault at 0 ip 0000000000000000 sp 00007fffb045e5c8 error 14 in pressure-vessel-launch[400000+14000]
[167810.185834] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167811.172764] pressure-vessel[562639]: segfault at 0 ip 0000000000000000 sp 00007ffeb5131418 error 14 in pressure-vessel-launch[400000+14000]
[167811.172769] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167825.898848] pressure-vessel[562690]: segfault at 0 ip 0000000000000000 sp 00007ffffedd3ca8 error 14 in pressure-vessel-launch[400000+14000]
[167825.898852] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167825.973028] pressure-vessel[562689]: segfault at 0 ip 0000000000000000 sp 00007ffe603f5308 error 14 in pressure-vessel-launch[400000+14000]
[167825.973032] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167826.879923] pressure-vessel[563058]: segfault at 0 ip 0000000000000000 sp 00007ffeedb92db8 error 14 in pressure-vessel-launch[400000+14000]
[167826.879927] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167844.072975] pressure-vessel[563109]: segfault at 0 ip 0000000000000000 sp 00007ffd16e87958 error 14 in pressure-vessel-launch[400000+14000]
[167844.072980] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167844.148372] pressure-vessel[563110]: segfault at 0 ip 0000000000000000 sp 00007ffe6843ced8 error 14 in pressure-vessel-launch[400000+14000]
[167844.148377] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167844.233747] pressure-vessel[563482]: segfault at 0 ip 0000000000000000 sp 00007ffd80ec5d48 error 14 in pressure-vessel-launch[400000+14000]
[167844.233751] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167844.351184] pressure-vessel[563494]: segfault at 0 ip 0000000000000000 sp 00007fffa2f904b8 error 14 in pressure-vessel-launch[400000+14000]
[167844.351188] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[167845.286181] pressure-vessel[563510]: segfault at 0 ip 0000000000000000 sp 00007ffdf660a208 error 14 in pressure-vessel-launch[400000+14000]
[167845.286186] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[168160.868943] pressure-vessel[565447]: segfault at 0 ip 0000000000000000 sp 00007ffe146e7758 error 14 in pressure-vessel-launch[400000+14000]
[168160.868947] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[168160.943483] pressure-vessel[565446]: segfault at 0 ip 0000000000000000 sp 00007ffcf10d46a8 error 14 in pressure-vessel-launch[400000+14000]
[168160.943487] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[168161.017918] pressure-vessel[565863]: segfault at 0 ip 0000000000000000 sp 00007ffeedd37fa8 error 14 in pressure-vessel-launch[400000+14000]
[168161.017922] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[168161.304162] pressure-vessel[565884]: segfault at 0 ip 0000000000000000 sp 00007ffe6deb93d8 error 14 in pressure-vessel-launch[400000+14000]
[168161.304167] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[168162.273558] pressure-vessel[565900]: segfault at 0 ip 0000000000000000 sp 00007ffede794078 error 14 in pressure-vessel-launch[400000+14000]
[168162.273563] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[168211.067702] pressure-vessel[566711]: segfault at 0 ip 0000000000000000 sp 00007ffec0d7c898 error 14 in pressure-vessel-launch[400000+14000]
[168211.067707] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[168211.141700] pressure-vessel[566712]: segfault at 0 ip 0000000000000000 sp 00007ffd9be766e8 error 14 in pressure-vessel-launch[400000+14000]
[168211.141704] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[168211.226554] pressure-vessel[567088]: segfault at 0 ip 0000000000000000 sp 00007ffe60a23568 error 14 in pressure-vessel-launch[400000+14000]
[168211.226559] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[168211.454606] pressure-vessel[567104]: segfault at 0 ip 0000000000000000 sp 00007ffd3aebcb68 error 14 in pressure-vessel-launch[400000+14000]
[168211.454611] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[168212.419878] pressure-vessel[567120]: segfault at 0 ip 0000000000000000 sp 00007ffdbe4378b8 error 14 in pressure-vessel-launch[400000+14000]
[168212.419882] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[168230.704836] pressure-vessel[567190]: segfault at 0 ip 0000000000000000 sp 00007ffdde77ca48 error 14 in pressure-vessel-launch[400000+14000]
[168230.704841] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[168230.780810] pressure-vessel[567191]: segfault at 0 ip 0000000000000000 sp 00007ffee35d6a68 error 14 in pressure-vessel-launch[400000+14000]
[168230.780814] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[168230.855138] pressure-vessel[567553]: segfault at 0 ip 0000000000000000 sp 00007fff68850cf8 error 14 in pressure-vessel-launch[400000+14000]
[168230.855142] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[168230.995755] pressure-vessel[567570]: segfault at 0 ip 0000000000000000 sp 00007ffc223eb4d8 error 14 in pressure-vessel-launch[400000+14000]
[168230.995759] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[168231.919188] pressure-vessel[567586]: segfault at 0 ip 0000000000000000 sp 00007ffec6ccda28 error 14 in pressure-vessel-launch[400000+14000]

**Comment by 414n** [comment]
> I don't know if it is the same bug I have proton GE installed on ~/.steam/root/compatibilitytools.d/ doesn't work. Also proton 5.13-2 doesn't work.

No, this issue is for system-wide Proton installs (i.e. under `/usr/share/steam` or `/usr/local/share/steam`).
I'd suggest that you create a new issue for your problem.
Also, please wrap long-ish logs in code blocks/triple backticks tags.

**Comment by smcv** [comment]
The original issue reported here should be fixed in the `client_beta` branch of `SteamLinuxRuntime_soldier`: soldier version 0.20201203.0 or later. The same symlinks that I suggested in https://github.com/ValveSoftware/steam-runtime/issues/302#issuecomment-734396567 are included in the runtime content from that version onwards.

Confirming what @414n said, if your custom build of Proton is in `~/.steam/root/compatibilitytools.d`, then this is not your bug.

**Comment by smcv** [comment]
@TheAquabat, please report a separate bug with the information requested in <https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information>. In your case please use "method 1": "method 2" will not necessarily tell us everything we need.

**Comment by TheAquabat** [comment]
> @TheAquabat, please report a separate bug with the information requested in https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information. In your case please use "method 1": "method 2" will not necessarily tell us everything we need.

sorry this was not a bug apparently, it was related to the gtk nocsd package. I'm having another issue now but I will report separetely .

**Comment by 414n** [comment]
@smcv I confirm that the issue is fixed in `soldier_0.20201203.0`.

Thank you everyone

**Comment by dearlygparted** [comment]
Hi, I've opted in to the Steam client beta and Steam Linux Runtime Soldier beta, but I'm still unable to use ProtonGE (5.21_GE_1-1). Has this really been fixed? Not sure what else I can do on my end.
