### ISSUE TITLE
Proton 5.13 + pressure-vessel: does not find PulseAudio if XDG_RUNTIME_DIR is not set

### ISSUE THREAD

**Issue by liskin** [ValveSoftware/steam-runtime#343]
#### Your system information

* Steam Runtime Version: steam-runtime_0.20201203.1
* Distribution (e.g. Ubuntu 18.04): Debian testing (updated almost daily)
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): https://gist.github.com/liskin/2d9bb8c488ea046c0d2d6e0bc62f04af
  
* Have you checked for system updates?: Yes
* Are you using the Steam Linux Runtime compatibility tool?: No, but Proton 5.13 afaik does

#### Please describe your issue in as much detail as possible:
When I run a game (tested on Fish Fillets 2, The Room and TrackMania Nations Forever), audio either doesn't work at all or it does, but it doesn't go through pulseaudio, so HDMI/Bluetooth output doesn't work. When the audio doesn't work, it's presumably because the audio device is being used by pulseaudio, so waiting for a while without having pavucontrol open helps as pulseaudio releases the device after some time of inactivity. When the audio does work and I open pavucontrol while the game is running, neither Steam nor the game is visible there, confirming that audio doesn't go through pulseaudio.

Here's a log with PRESSURE_VESSEL_VERBOSE=1: [pressure-vessel.log](https://github.com/ValveSoftware/steam-runtime/files/5744697/pressure-vessel.log)

#### Steps for reproducing this issue:

1. run `pax11publish -e`
2. select Proton 5.13 as compatibility tool
3. run game
4. check audio and if it happens to work, check pavucontrol whether it goes through pulseaudio

Arguably running `pax11publish -e` locally is a bad idea as it sets `PULSE_SERVER` to a hostname instead of a UNIX socket, but everything else on my system seems to work well, so it's a bit weird.

**Comment by liskin** [comment]
I tried `PRESSURE_VESSEL_SHELL=instead` and ran `…/proton run winecfg`, it shows `winealsa.drv` as the audio driver, so I tried to look for a pulseaudio plugin:

```
(steamrt soldier 0.20201203.0)tomi@notes:/data/tomi/.steam/steamapps/common/Fish Fillets 2$ find / -name '*asound*pulse*' 2>/dev/null
/data/tomi/.steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_conf_pulse.so
/data/tomi/.steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_ctl_pulse.so
/data/tomi/.steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_pulse.so
/data/tomi/.steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/alsa-lib/libasound_module_conf_pulse.so
/data/tomi/.steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/alsa-lib/libasound_module_ctl_pulse.so
/data/tomi/.steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/alsa-lib/libasound_module_pcm_pulse.so
/data/tomi/.steam/ubuntu12_32/steam-runtime.old/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_conf_pulse.so
/data/tomi/.steam/ubuntu12_32/steam-runtime.old/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_ctl_pulse.so
/data/tomi/.steam/ubuntu12_32/steam-runtime.old/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_pulse.so
/data/tomi/.steam/ubuntu12_32/steam-runtime.old/usr/lib/i386-linux-gnu/alsa-lib/libasound_module_conf_pulse.so
/data/tomi/.steam/ubuntu12_32/steam-runtime.old/usr/lib/i386-linux-gnu/alsa-lib/libasound_module_ctl_pulse.so
/data/tomi/.steam/ubuntu12_32/steam-runtime.old/usr/lib/i386-linux-gnu/alsa-lib/libasound_module_pcm_pulse.so
/run/host/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_conf_pulse.so
/run/host/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_ctl_pulse.so
/run/host/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_pulse.so
/run/host/usr/lib/i386-linux-gnu/alsa-lib/libasound_module_conf_pulse.so
/run/host/usr/lib/i386-linux-gnu/alsa-lib/libasound_module_ctl_pulse.so
/run/host/usr/lib/i386-linux-gnu/alsa-lib/libasound_module_pcm_pulse.so
```

So it is reachable, but it doesn't seem ALSA is configured to use it:
```
(steamrt soldier 0.20201203.0)tomi@notes:/data/tomi/.steam/steamapps/common/Fish Fillets 2$ grep -c pulse /usr/share/alsa/alsa.conf 2>/dev/null
0
$ ls -la /etc/alsa/conf.d /etc/asound.conf ~/.asoundrc
ERROR: ld.so: object '/data/tomi/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ls: cannot access '/etc/alsa/conf.d': No such file or directory
ls: cannot access '/etc/asound.conf': No such file or directory
ls: cannot access '/home/tomi/.asoundrc': No such file or directory
```

**Comment by TTimo** [comment]
I think Proton should be trying to initialize pulseaudio first, and ALSA is only a fallback. There are no obvious problems in the Pressure Vessel logs, studying the PROTON_LOG=1 logs may indicate why pulseaudio init is failing. I suspect this is specific to your setup, less likely to be a Debian wide problem.

**Comment by kisak-valve** [comment]
Hello @liskin, A proton log of an affected game with pulseaudio logging might give some additional insight. Please add the following logging channels: +pulse,+timestamp

You can create logs with custom channels by:

1) Go to your Proton 5.13-4 folder (~/.steam/steam/steamapps/common/Proton 5.13)
2) Copy user_settings.sample.py and rename as user_settings.py (cp user_settings.sample.py user_settings.py)
3) Edit user_settings.py and add these channels to the end of the "WINEDEBUG" line.

@414n, @MurdoMaclachlan, there's a chance you've also seen this issue recently or a close variant. Please confirm if your systems are configured to use pulseaudio and Proton is hitting an assert with alsa failing to open the audio device. If they do, then try gathering a Proton log with the above info and attach it as a file. (Proton logs compress well if needed). Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) with the extended diagnostics information and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by liskin** [comment]
I tried this inside of the xterm launched via `PRESSURE_VESSEL_SHELL=instead` instead as it's simpler and more interactive:

```
WINEDEBUG=+pulse,+timestamp /data/tomi/.steam/steamapps/common/Proton\ 5.13/proton run winecfg
```

When I do this, I see winealsa.drv as the audio driver, and when I force pulse through protontricks, there's no audio driver at all. The log says:

```
======================
Proton: 1607520831 proton-5.13-4
SteamGameId: 33950
Command: ['winecfg']
Options: {'forcelgadd'}
SteamLinuxRuntime: v0.20201124.0-2-g0f9c98f
pressure-vessel: 0.20201203.0+srt1 scout 0.20201203.1
soldier: 0.20201203.0 soldier 0.20201203.0
======================
ERROR: ld.so: object '/data/tomi/.steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
esync: up and running.
ERROR: ld.so: object '/data/tomi/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Setting breakpad minidump AppID = 33950
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198023344306 [API loaded no]
3413990.093:00d8:trace:pulse:pulse_test_connect Name: winecfg.exe
3413990.093:00d8:trace:pulse:pulse_test_connect libpulse protocol version: 32. API Version 12
3413990.093:00d8:trace:pulse:pulse_contextcallback State change to 1
3413990.093:00d8:warn:pulse:pulse_contextcallback Context failed: Connection refused
3413990.095:00d8:err:mmdevapi:DllGetClassObject Driver initialization failed
3413990.095:00d8:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\\windows\\system32\\mmdevapi.dll"
3413990.095:00d8:err:ole:CoGetClassObject no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x1
pid 721 != 720, skipping destruction (fork without exec?)
```

So the interesting bit is:
```
3413990.093:00d8:warn:pulse:pulse_contextcallback Context failed: Connection refused
```

Now if inside of that environment I do this:
```
LD_LIBRARY_PATH=/run/host/usr/lib/x86_64-linux-gnu/pulseaudio:/run/host/usr/lib/x86_64-linux-gnu:/run/host/lib/x86_64-linux-gnu /run/host/usr/bin/paplay Sounds/Laser/laserup.wav
```
it plays just fine.

It's really strange but I will dig a bit deeper, assuming it's a problem in my setup.

**Comment by liskin** [comment]
When I strace the pulseaudio daemon, there's no activity at all, meaning wine doesn't even try to connect to it. When I strace proton, I see it reads /run/user/1000/pulse/config, then connects to the X server through /tmp/.X11-unix/X99, presumably to read the PULSE_SERVER and PULSE_COOKIE properties from the root window, and then proceeds to resolve PULSE_SERVER to my public IPv{4,6} and attempt to connect to those addresses, port 4713, which obviously fails as I haven't enabled network access in pulseaudio. It then gives up.

/run/user/1000/pulse/native is not mentioned in the strace at all.

So, um, maybe something is wrong with my setup and the PULSE_SERVER property is not set correctly, but why does paplay work fine? Why does proton 5.0 work fine? We need to go deeper. :-)

**Comment by liskin** [comment]
All right, it seems I accidentally ran `pax11publish -e` in this session some time ago which set PULSE_SERVER to my hostname instead of `"{…}unix:/run/user/1000/pulse/native"`. Re-running start-pulseaudio-x11 makes audio in Proton 5.13 work again.

Still, it's a bit strange that Proton 5.0 tried the unix socket anyway, and so does paplay and all the other apps on my system.

**Comment by liskin** [comment]
Anyway, I'll close this. If you folks wish to check if proton/wine should be trying the local socket anyway, feel free to do so, but my problem is definitely caused by me messing up the PULSE_SERVER property and I've fixed this. Thanks for pointing me in the right direction.

**Comment by 414n** [comment]
@kisak-valve I was just discussing that issue with some folks on Discord when you "summoned" me here :grimacing:.
Happy to oblige, here's:

 - confirmation that pulseaudio is in use (`pactl list`): [pactl_list.txt](https://github.com/ValveSoftware/steam-runtime/files/5749118/pactl_list.txt)
 - my updated system info: [gist](https://gist.github.com/414n/34891616266f2d4e4489173e8bbee632)
 - the complete error log for "The Witcher 3" running on Proton-5.13: [steam-292030.log.gz](https://github.com/ValveSoftware/steam-runtime/files/5749104/steam-292030.log.gz) (a snippet was reported [here](https://github.com/ValveSoftware/Proton/issues/607#issuecomment-743436942)).
 
Do note that for "The Witcher 3" I recreated the whole wine prefix, as I previously installed `xact` via winetricks to solve the issue.

**Comment by wundrweapon** [comment]
This should definitely be either renamed and reopened, or replaced with a new issue. I have yet to find a game that actually plays audio with Proton 5.13, even without messing with Wine settings, pressure vessel (whatever that means), environment variables, or PulseAudio. My system info (i.e. the output of `lshw`) can again be found [here](https://pastebin.com/vU5B1RBY).

**Comment by TTimo** [comment]
@414n @wundrweapon please consider reporting a Proton log produced as explained in https://github.com/ValveSoftware/steam-runtime/issues/343#issuecomment-751783811 - this will (likely) confirm that Proton is failing to initialize pulseaudio

**Comment by MurdoMaclachlan** [comment]
Whoops, just saw this. Although I'm certain PulseAudio is what my system is configured to use, it isn't mentioned anywhere in the output from `pact list` ([pactl_list.txt](https://github.com/ValveSoftware/steam-runtime/files/5754880/pactl_list.txt)). That being said, I don't believe I personally encountered this issue, so I'm not surprised there are differences, even if I am confused that it isn't showing in the output.

My system information can be found [here](https://gist.github.com/MurdoMaclachlan/5ab634db5eaeedff1d318ee65a5882df).

**Comment by 414n** [comment]
@TTimo sorry, forgot to add the `+pulse` channel to WINEDEBUG before. 
However, after setting it first in Proton `user_settings.py`, then in the launch options for the game I could not find even a single `pulse` occurrence in the log (here is the log with `WINEDEBUG="+alsa,+pulse,+timestamp,+pid,+tid,+seh,+debugstr,+loaddll,+mscoree"`: [steam-292030.log.gz](https://github.com/ValveSoftware/steam-runtime/files/5755316/steam-292030.log.gz)).
I then tried adding `+relay` to test if I did something wrong that did not set the channels properly, but then I got the relay trace as expected, so I guess there's really nothing to see on wine pulse channel.

**Comment by wundrweapon** [comment]
Per TTimo's request, [here](https://gist.github.com/wundrweapon/df73648490ff2d9ad4f09291cda30e0b) is my sysinfo gist, and [attached](https://github.com/ValveSoftware/steam-runtime/files/5755613/steam-284460.log.gz) is a gzip-compressed log from DeadCore using `+pulse` and `+alsa` in `user_settings.py`  
Quickly grep'ing for "pulse" reveals the module is loaded, something goes wrong, then it unloads.

Side comment: I know kisak said "Proton logs compress well" but wow, I was not expecting a 29KB file to become 352B with one pass of `xz -9e`. That's impressive, even if GitHub doesn't allow .xz uploads.

**Comment by smcv** [comment]
@414n: Where does Slackware put its PulseAudio socket? Does PulseAudio work in Flatpak apps on the same system? One possible cause for this is that Slackware is using an unusual PulseAudio setup, and the code in pressure-vessel that shares PA between host and container (borrowed from Flatpak) doesn't know where to find it.

@wundrweapon: Same question, but for Void?

To give you an idea of what to look for, on a Debian system with systemd, my PulseAudio socket is `$XDG_RUNTIME_DIR/pulse/native` (equivalently `/run/user/1000/pulse/native`). pressure-vessel also looks in `$PULSE_SERVER` and in `/var/run/pulse/native` (for the system-wide PA instance on SteamOS), or reads the files `${XDG_CONFIG_HOME:-$HOME/.config}/pulse/client.conf` and `/etc/pulse/client.conf` looking for `default-server`. Flatpak tries all of those paths except for `/var/run/pulse/native`.

If your operating systems don't have an `$XDG_RUNTIME_DIR` (usually set by `systemd-logind` or `elogind`), then we might need a cleverer way to find PulseAudio's listening socket.

**Comment by smcv** [comment]
From PulseAudio source code, both Flatpak and pressure-vessel should probably also be looking at `$PULSE_RUNTIME_PATH/native`, `~/.pulse/${machine_id}-runtime` and `${XDG_CONFIG_HOME:-$HOME/.config}/pulse/${machine_id}-runtime` where `${machine_id}` is the contents of either `/etc/machine-id` or `/var/lib/dbus/machine-id`. They currently don't.

**Comment by 414n** [comment]
@smcv It seems that the socket is put under `/tmp` (looked up via `lsof`). I found several methods to obtain this information:

 - the `pactl info` command output: 

```sh
$ LC_ALL=C pactl info
Server String: unix:/tmp/pulse-PKdhtXMmr18n/native
Library Protocol Version: 31
Server Protocol Version: 31
Is Local: yes
Client Index: 30
Tile Size: 65472
User Name: alan
Host Name: <REDACTED>
Server Name: pulseaudio
Server Version: 9.0-rebootstrapped
Default Sample Specification: s16le 5ch 48000Hz
Default Channel Map: front-left,front-right,front-center,rear-left,rear-right
Default Sink: alsa_output.pci-0000_00_1b.0.analog-surround-51
Default Source: alsa_input.pci-0000_00_1b.0.analog-stereo
Cookie: 8f58:5721
```
  - a dbus query:

```sh
$ qdbus org.pulseaudio.Server /org/pulseaudio/server_lookup1 org.PulseAudio.ServerLookup1.Address
unix:path=/tmp/pulse-PKdhtXMmr18n/dbus-socket
```

 - a X11 properties query:

```sh
$ xprop -root -notype PULSE_SERVER | tr -d ' '
PULSE_SERVER="{5760c2b29f10028db851b4835290e145}unix:/tmp/pulse-PKdhtXMmr18n/native"
```

Currently I have no flatpak utility nor package installed, but if a test is needed I can try setting it all up.

I tried forcing the `PULSE_SERVER` environment variable to the address found via those two methods when launching a Proton game (The Witcher 3), however I get this line in the logs:

```
pressure-vessel-launcher[2741]: Ignoring request to set PULSE_SERVER="unix:/tmp/pulse-PKdhtXMmr18n/native" because it was locked to "<unset>"
```
so it seems it is not overridable on launch.

**Comment by wundrweapon** [comment]
@smcv my system has neither systemd-logind (or any other systemd components) nor elogind. Unsurprisingly, environment variables `XDG_RUNTIME_DIR`, `PULSE_SERVER`, and `PULSE_RUNTIME_PATH` are all unset. I ran `pactl info` like @414n and also found my Server String in `/tmp`, specifically it was `/tmp/pulse-AYkIsa0nnIEV/native`. A friend who also uses Void and has the same audio issues as me found theirs to be `/tmp/pulse-PKdhtXMmr18n/native` via the same command.

**Comment by smcv** [comment]
I think this new/reopened issue (not directly related to @liskin's misconfiguration, but with the same high-level symptom) is probably triggered by not having an `XDG_RUNTIME_DIR`. A system with either systemd-logind or elogind would have that, assuming its PAM module is correctly set up, but systems with neither of those might not.

Please try this workaround:

* Completely exit from Steam
* Find the appropriate socket, which I'll refer to here as `/tmp/pulse-whatever/native`, by any of the methods @414n described
* Run Steam as `PULSE_SERVER=unix:/tmp/pulse-whatever/native steam`, substituting the correct path
* Launch a Proton game

If that works and uses PA, then we can probably solve this by teaching (Flatpak and) pressure-vessel to do approximately the same thing that `pactl info` does.

**Comment by smcv** [comment]
> Ignoring request to set PULSE_SERVER="unix:/tmp/pulse-PKdhtXMmr18n/native" because it was locked to "<unset>"

This is because the configured launch options take effect too late for pressure-vessel to be able to make use of them during container setup.

**Comment by 414n** [comment]
> I think this new/reopened issue (not directly related to @liskin's misconfiguration, but with the same high-level symptom) is probably triggered by not having an `XDG_RUNTIME_DIR`. A system with either systemd-logind or elogind would have that, assuming its PAM module is correctly set up, but systems with neither of those might not.

I concur. Next Slackware version will be elogind-based for what I've seen but, for now, no `XDG_RUNTIME_DIR`.

> Please try this workaround:
> 
>     * Completely exit from Steam
> 
>     * Find the appropriate socket, which I'll refer to here as `/tmp/pulse-whatever/native`, by any of the methods @414n described
> 
>     * Run Steam as `PULSE_SERVER=unix:/tmp/pulse-whatever/native steam`, substituting the correct path
> 
>     * Launch a Proton game
> 
> 
> If that works and uses PA, then we can probably solve this by teaching (Flatpak and) pressure-vessel to do approximately the same thing that `pactl info` does.

Thanks for the suggestion, but it still doesn't work:

```
pressure-vessel-launcher[9181]: Ignoring request to set PULSE_SERVER="unix:/tmp/pulse-PKdhtXMmr18n/native" because it was locked to "<unset>"
```

Seems like the variable override is kind of "blacklisted" and forced unset?

Complete output of the following command: [steam.log.gz](https://github.com/ValveSoftware/steam-runtime/files/5767387/steam.log.gz)
```sh
PULSE_SERVER="$(LC_ALL=C pactl info  | awk -v FPAT='unix:/.*' '/Server String/ {print $1}')" \
LC_ALL=C \
LANG=C \
PRESSURE_VESSEL_VERBOSE=1 \
steam
```

**Comment by wundrweapon** [comment]
> Please try this workaround:
> - Completely exit from Steam
> - Find the appropriate socket, which I'll refer to here as `/tmp/pulse-whatever/native`, by any of the methods 414n described
> - Run Steam as `PULSE_SERVER=unix:/tmp/pulse-whatever/native steam`, substituting the correct path
> - Launch a Proton game

This works! Mostly, anyways. World at War has no audio with 5.13-4, but 5.21-GE-1 works. DeadCore works with both, as does Just Cause 3. Here's a robust POSIX shell launch script, for anyone who wants it.

```sh
#!/bin/sh
PULSE_SERVER="unix:$(pactl info | grep "Server String:" | awk '{print $3}')" exec steam
```

**Comment by liskin** [comment]
This is probably even simpler than the grep/awk "robustness" :-))
```
eval $(pax11publish -i)
exec stam "$@"
```

**Comment by smcv** [comment]
> Seems like the variable override is kind of "blacklisted" and forced unset?

This message is because its value is only valid *outside* the container, and pressure-vessel has to parse it, figure out where the actual socket is, bind-mount the socket inside the container (at a different location!), and reset PA's environment variables to values that will be valid inside the container (`PULSE_SERVER=unix:/run/user/1000/pulse/native` and `PULSE_CLIENTCONFIG=/run/user/1000/pulse/config`).

Then, the launch options get applied, so the environment is different; we want to apply any environment variables that got changed by the launch options, but without undoing any of the environment variable changes that we made in order to make the container work. So `PULSE_SERVER` should have been "locked" to `unix:/run/user/1000/pulse/native` to keep it valid inside the container. It seems `PULSE_SERVER` is getting unset instead, somewhere... I'm not sure why.

I'm not sure why this is working for @wundrweapon on Void, but not for @414n on Slackware. @wundrweapon, please could you capture a log with this workaround in use?

> Next Slackware version will be elogind-based for what I've seen

That's good - increasingly many IPC client/server pairs either benefit from having `XDG_RUNTIME_DIR` (like PulseAudio and Pipewire), or require it (like Wayland).

**Comment by smcv** [comment]
> The runtime information tool is preparing a report, please wait...

If you're capturing a system info report, please wait for it to finish - it takes a few seconds, because among other things it has to go through all the libraries in the Steam Runtime and check whether it can load them.

**Comment by wundrweapon** [comment]
> ```
> eval $(pax11publish -i)
> exec steam "$@"
> ```

This does not work on my machine. Just a little testing reveals `PULSE_SERVER` isn't set, and `$@` isn't modified:
```sh
#!/bin/sh
eval $(pax11publish -i)
[ -z "$PULSE_SERVER" ] && echo "PS empty" || echo $PUSE_SERVER
[ -z "$@" ] && echo "cashat empty" || echo "$@"
```
I also updated my previous script because I found a way to cut awk out of the equation, though it may be slower. Someone else can test that; my computer insists they both take 0.00 seconds even to do it 200 times (echoing the result instead of running steam).

**Comment by wundrweapon** [comment]
I didn't see the point where @smcv asked for a log. [Here](https://github.com/ValveSoftware/steam-runtime/files/5773488/steam-284460.log.gz)'s DeadCore, Proton 5.13-4, with my workaround in use, gzipped. `+pulse` and `+alsa` in `user_settings.py`, just as before.

**Comment by smcv** [comment]
@wundrweapon: sorry, I wasn't clear. The log I wanted to see is the output from the pressure-vessel container tool rather than from Proton, which appears on Steam's stdout/stderr when you do similar to <https://github.com/ValveSoftware/steam-runtime/issues/343#issuecomment-754311676>. It should look similar to what @414n attached in that comment, with messages involving `pressure-vessel-wrap`. Mostly, I want to be able to compare it with @414n's log to figure out why the workaround I suggested works for you but not for @414n.

**Comment by wundrweapon** [comment]
Alright, confusion time.

Running this:
```zsh
PULSE_SERVER="unix:$(pactl info | grep "Server String:" | awk '{print $3}')" PRESSURE_VESSEL_VERBOSE=1 LC_ALL=C LANG=C steam &> steam.log
```
I see several lines beginning with `pressure-vessel` that happily say `PULSE_SERVER=unix:/tmp/pulse-AYkIsa0nnIEV/native`, and then there's this one: `pressure-vessel-launcher[24223]: Ignoring request to set PULSE_SERVER="unix:/tmp/pulse-AYkIsa0nnIEV/native" because it was locked to "<unset>"`. Despite that, audio worked just fine. That is the only line which says this.

Here's the part that really gets me. Take that grep-awk combo, and replace it with a single grep as described previously: `pactl info | grep -oP "(?<=Server String: ).+"`  
Despite the restulant string being byte-for-byte identical, the audio won't work.
[Here's my log, please don't doxx me](https://github.com/ValveSoftware/steam-runtime/files/5778472/steam.log.gz)

**Comment by 414n** [comment]
> Then, the launch options get applied, so the environment is different; we want to apply any environment variables that got changed by the launch options, but without undoing any of the environment variable changes that we made in order to make the container work. So `PULSE_SERVER` should have been "locked" to `unix:/run/user/1000/pulse/native` to keep it valid inside the container. It seems `PULSE_SERVER` is getting unset instead, somewhere... I'm not sure why.

I think there's something strange in how that variable is managed. I ran these commands inside a container with and without the `PULSE_SERVER` variable override:

```sh
set | grep ^PULSE
ls -l /run/user/1000/pulse
```

with the following results:

 - with `PULSE_SERVER` override:

```sh
$ PULSE_SERVER="$(LC_ALL=C pactl info  | awk -v FPAT='unix:/.*' '/Server String/ {print $1}')" \
LC_ALL=en_US \
/PATH/TO/SteamLinuxRuntime_soldier/_v2-entry-point \
  --deploy=soldier \
  --suite=soldier \
  --verb=run  -- \
  bash -c "set | grep ^PULSE; ls -l /run/user/1000/pulse"
PULSE_CLIENTCONFIG=/run/user/1000/pulse/config
total 4
-rw------- 0 alan users 14 Jan  7 12:18 config
srwxrwxrwx 1 alan users  0 Jan  7 10:28 native
```

 - without `PULSE_SERVER` override:
 
```sh
$ LC_ALL=en_US \
/PATH/TO/SteamLinuxRuntime_soldier/_v2-entry-point \
  --deploy=soldier \
  --suite=soldier \
  --verb=run  -- \
  bash -c "set | grep ^PULSE; ls -l /run/user/1000/pulse"
ls: cannot access '/run/user/1000/pulse': No such file or directory
```

When `PULSE_SERVER` is overridden with the correct (host) socket path, the socket seems to be indeed bound to `/run/user/1000/pulse/native` inside the container, however the `PULSE_SERVER` variable in that environment is not set to point there (while `PULSE_CLIENTCONFIG` seems to be correctly remapped).
When `PULSE_SERVER` is not specified and the runtime does not pick up the host socket path, no `PULSE_*` environment variables nor socket bind mount get defined inside the container.

**Comment by smcv** [comment]
> When PULSE_SERVER is not specified and the runtime does not pick up the host socket path, no PULSE_* environment variables nor socket bind mount get defined inside the container.

This is expected, at the moment. If the container launcher can't detect where your PulseAudio socket is on the host, it assumes you don't have PulseAudio at all, and doesn't do anything special to make it available across the container boundary.

The main problem causing this issue is that libpulse tries lots of mechanisms to find the PulseAudio socket (including environment variables, X11, D-Bus, or using a well-known path in `$XDG_RUNTIME_DIR` if you have one), but the code we recycled from Flatpak (`flatpak_run_add_pulseaudio_args()` in `pressure-vessel/flatpak-run.c`, if you're following along in [the source code](https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/)) only implements the simpler ones.

By asking you to specify `PULSE_SERVER` on the host, I'm trying to work around this by making sure your PA server is advertised via one of the mechanisms that the Flatpak-derived code *does* understand. Unfortunately, that doesn't seem to be working either: if it had worked, then `PULSE_SERVER` would get set (to a different value!) inside the container. For @wundrweapon, it works anyway after applying this workaround (I don't yet understand why!) but for you, it doesn't.

What version of PulseAudio are you each using on the host system, and what patches does your distribution apply to it?

**Comment by smcv** [comment]
> > eval $(pax11publish -i)
>
> This does not work on my machine.

Depending what version and configuration you are running, PulseAudio might advertise its presence in various different ways (environment variables, X11, D-Bus, or using a well-known path in `$XDG_RUNTIME_DIR` if you have one). The libpulse client library tries looking for it in various ways.

On the host system, if at least one of the ways the libpulse client library looks for it matches up with at least one of the ways the server advertises itself, then audio will work on the host system.

However, the container's filesystem and the host system's filesystem are different. For audio to work in the container, pressure-vessel needs to adjust things to work across the container boundary.

`pax11publish -i` specifically looks at *one* of the discovery mechanisms: the one that uses X11. If your PulseAudio server is not advertising itself via X11, then that isn't going to work.

**Comment by smcv** [comment]
One thing that might be interfering with this is if PulseAudio uses "abstract" Unix sockets. To check this, please try:

```
netstat --unix --listening | grep pulse
```

or

```
ss --unix --listening | grep pulse
```

If you see something like `/tmp/pulse-AYkIsa0nnIEV/native`, then that's a path-based Unix socket, which is what the Flatpak-derived code assumes will happen.

If, instead, you see something like `@/tmp/pulse-AYkIsa0nnIEV/native`, then that's an abstract Unix socket, which it doesn't handle.

**Comment by smcv** [comment]
Right, I think I see what's going on here. In both your logs, with the `PULSE_SERVER=unix:/whatever steam` workaround, pressure-vessel adds `PULSE_SERVER=unix:/run/user/1000/pulse/native` and `PULSE_CLIENTCONFIG=/run/user/1000/pulse/config` to the environment variables for `bwrap`. However, it *also* adds `--unsetenv PULSE_SERVER` to the `bwrap` command-line, which has a higher priority. Later in the log, we can see that `pressure-vessel-launcher` gets run with `PULSE_CLIENTCONFIG` set correctly, but `PULSE_SERVER` unset.

So the bugs we need to solve to get this fully working are:

* stop adding `--unsetenv PULSE_SERVER` when we have given `PULSE_SERVER` a proper value - this is quite a high priority, because it has no good workaround and could be breaking other things too
* implement more ways to find the PulseAudio socket (X11 and/or D-Bus) so that the workaround of setting `PULSE_SERVER` is unnecessary - this is more complicated and might not happen immediately

I still don't really understand why it manages to work anyway for @wundrweapon... but if we can solve at least the first of those two bugs then it won't matter.

**Comment by 414n** [comment]
> What version of PulseAudio are you each using on the host system, and what patches does your distribution apply to it?

Pulseaudio-9.0, with a bunch of patches applied: [package source link](https://mirrors.slackware.com/slackware/slackware64-14.2/source/l/pulseaudio/). Inside the `pulseaudio.SlackBuild` script (after line 71) there's an explanation for why those patches get applied.

**Comment by smcv** [comment]
> stop adding --unsetenv PULSE_SERVER when we have given PULSE_SERVER a proper value - this is quite a high priority, because it has no good workaround and could be breaking other things too

Looking into the code in more detail, I think this part is actually fixed already. If I'm understanding correctly, the current beta (pressure-vessel version 0.20210105.0) still has this bug, but the *next* beta probably won't, because we handle environment variables differently.

> implement more ways to find the PulseAudio socket (X11 and/or D-Bus)

`$PULSE_SERVER` is the highest priority, and is handled already. @liskin's original issue report might have been because the incorrect `--unsetenv PULSE_SERVER` caused this to be skipped, which meant X11 was tried next.

The next thing tried is X11. Current versions of PulseAudio will [only look for the server in X11 if run from a remote ssh session](https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/commit/79a8efb45cb8304967baa2e8c6d6156478ce19d9), and Steam games seem vanishingly unlikely to be usable with remote ssh, so it seems reasonable to skip that one (which is good, because Flatpak and pressure-vessel don't currently connect to X11, and it'll be simplest if we keep them that way).

The next thing tried is `${runtime}/native`, where `${runtime}` can either be `$PULSE_RUNTIME_PATH`, or `$XDG_RUNTIME_DIR/pulse`, or a temporary directory in `/tmp` that is pointed to by a symlink `~/.pulse/${machine_id}-runtime` or `${XDG_CONFIG_HOME:-$HOME/.config}/pulse/${machine_id}-runtime` - where ${machine_id} is either the contents of `/etc/machine-id`, or the contents of `/var/lib/dbus/machine-id`, or the hostname. Flatpak and pressure-vessel don't implement this fully: they assume the runtime directory is always `$XDG_RUNTIME_DIR/pulse` and ignore the other possibilities.

Next is `/var/run/pulse/native`, which is handled already in pressure-vessel, although not in Flatpak (I should probably upstream that to Flatpak).

Finally there are some TCP sockets (which are probably a bad idea to actually use, but won't be affected by the container anyway).

None of this seems to have changed since 9.0, which seems like a good cutoff point for what's realistic to support.

**Comment by liskin** [comment]
> `$PULSE_SERVER` is the highest priority, and is handled already. @liskin's original issue report might have been because the incorrect `--unsetenv PULSE_SERVER` caused this to be skipped, which meant X11 was tried next.
> 
> The next thing tried is X11. Current versions of PulseAudio will [only look for the server in X11 if run from a remote ssh session](https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/commit/79a8efb45cb8304967baa2e8c6d6156478ce19d9), and Steam games seem vanishingly unlikely to be usable with remote ssh, so it seems reasonable to skip that one (which is good, because Flatpak and pressure-vessel don't currently connect to X11, and it'll be simplest if we keep them that way).

I feel like my issue was more likely caused by the above mentioned patch not being included in the runtime's version of pulseaudio libs. I had my hostname in the `PULSE_SERVER` **X11 property**, nowhere else. Without pressure vessel and steam's runtime, everything worked, but inside of it, the property was likely consulted and thus wine only tried to connect over tcp/udp, not unix.

Not that it matters, really. :-)

**Comment by smcv** [comment]
@414n, @wundrweapon: Since neither of you have an `XDG_RUNTIME_DIR`, I'm guessing that you have a symlink in `~/.pulse/` as described above, pointing to the directory in `/tmp` that contains the `native` socket. Please could you both confirm whether that is true?

You don't need to show me the actual machine ID (it's a persistent identifier for the machine and I can understand if you want to avoid pasting it on an issue report), but please confirm whether things are set up the way I expect.

I would expect something like this:

```
$ cat /etc/machine-id
cat: /etc/machine-id: No such file or directory
$ cat /var/lib/dbus/machine-id
aaaabbbbccccddddeeeeffff00001111
$ ls -l ~/.pulse
ls: cannot access '/home/me/.pulse': No such file or directory
$ ls -l "${XDG_CONFIG_HOME:-$HOME/.config}"/pulse
lrwxrwxrwx ... aaaabbbbccccddddeeeeffff00001111-runtime -> /tmp/pulse-AYkIsa0nnIEV
... and maybe some other files which I'm not interested in ...
$ ls -l /tmp/pulse-AYkIsa0nnIEV
srw-rw-rw- ... native
-rw------- ... pid
```

Variations: you might have `~/.pulse` instead of `~/.config/pulse`, and you might have `/etc/machine-id`.

**Comment by smcv** [comment]
@kisak-valve, please could you retitle this to reflect the scope of the issue that @414n and @wundrweapon are having, so that we don't get this issue report repurposed to a different root cause with the same top-level symptom for a second time? Something like: "Proton 5.13 + pressure-vessel: does not find PulseAudio if XDG_RUNTIME_DIR is not set".

This is primarily going to affect non-systemd, non-elogind machines, because systemd-logind and elogind do set up `XDG_RUNTIME_DIR`.

**Comment by smcv** [comment]
> I feel like my issue was more likely caused by the above mentioned patch not being included in the runtime's version of pulseaudio libs

Ah, you're right: soldier is based on Debian 10, which only has PA 12, and that patch was new in PA 13. I think we can write off your original issue as being a one-off local misconfiguration. If it affects other people then we can consider backporting that patch into soldier's libpulse0, but we're trying to keep local patches in soldier to a minimum.

Sorry for the bugmail noise from this issue being repurposed for a different root cause of the same symptoms.

**Comment by liskin** [comment]
> Sorry for the bugmail noise from this issue being repurposed for a different root cause of the same symptoms.

No worries. I wasted some of your time by reporting an issue that was caused by my own misconfiguration, now I consider it polite to lurk for a while and help others, and when I feel I've done enough, I can unsubscribe. :-)

(Thanks for all the work you guys are doing, btw!)

**Comment by smcv** [comment]
> implement more ways to find the PulseAudio socket (X11 and/or D-Bus)

If my analysis is correct, I believe this will be fixed by https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/merge_requests/212 in pressure-vessel, and https://github.com/flatpak/flatpak/pull/4059 for the original code in Flatpak.

**Comment by 414n** [comment]
> @414n, @wundrweapon: Since neither of you have an `XDG_RUNTIME_DIR`, I'm guessing that you have a symlink in `~/.pulse/` as described above, pointing to the directory in `/tmp` that contains the `native` socket. Please could you both confirm whether that is true?

Yes, that's `~/.config/pulse/<MACHINE_ID>-runtime` for me on Slackware.

> You don't need to show me the actual machine ID (it's a persistent identifier for the machine and I can understand if you want to avoid pasting it on an issue report), but please confirm whether things are set up the way I expect.
> 
> I would expect something like this:
> 
> ```
> $ cat /etc/machine-id
> cat: /etc/machine-id: No such file or directory
> $ cat /var/lib/dbus/machine-id
> aaaabbbbccccddddeeeeffff00001111
> $ ls -l ~/.pulse
> ls: cannot access '/home/me/.pulse': No such file or directory
> $ ls -l "${XDG_CONFIG_HOME:-$HOME/.config}"/pulse
> lrwxrwxrwx ... aaaabbbbccccddddeeeeffff00001111-runtime -> /tmp/pulse-AYkIsa0nnIEV
> ... and maybe some other files which I'm not interested in ...
> $ ls -l /tmp/pulse-AYkIsa0nnIEV
> srw-rw-rw- ... native
> -rw------- ... pid
> ```

Here's what those commands return on my system:

```sh
$ cat /etc/machine-id
cat: /etc/machine-id: No such file or directory
$ cat /var/lib/dbus/machine-id
<MACHINE_ID>
$ ls -l ~/.pulse
ls: cannot access '/home/alan/.pulse': No such file or directory
$ ls -l "${XDG_CONFIG_HOME:-$HOME/.config}"/pulse
total 112
-rw-r--r-- 1 alan users 28672 Jan  3 14:32 <MACHINE_ID>-card-database.tdb
-rw-r--r-- 1 alan users    48 Jan  7 10:28 <MACHINE_ID>-default-sink
-rw-r--r-- 1 alan users    42 Jan  7 10:28 <MACHINE_ID>-default-source
-rw-r--r-- 1 alan users 16384 Dec 25 15:08 <MACHINE_ID>-device-manager.tdb
-rw-r--r-- 1 alan users 28672 Jan  7 16:51 <MACHINE_ID>-device-volumes.tdb
lrwxrwxrwx 1 alan users    23 Jan  7 10:28 <MACHINE_ID>-runtime -> /tmp/pulse-PKdhtXMmr18n
-rw-r--r-- 1 alan users 28672 Jan  5 16:17 <MACHINE_ID>-stream-volumes.tdb
-rw------- 1 alan users   256 Jan  4 22:59 cookie
$ ls -l /tmp/pulse-PKdhtXMmr18n/
total 4
srwxrwxrwx 1 alan users 0 Jan  7 10:28 native
-rw------- 1 alan users 5 Jan  7 10:28 pid
```

`/etc/machine-id` is not available, as that's managed by systemd IIRC, but the dbus one is there, as is the `~/.config/pulse` directory with the symlink to the temp directory used by pulse for its socket file.

**Comment by smcv** [comment]
> Here's what those commands return on my system

Good, that's what I expected (basically the same as the Debian 10 VM with sysvinit that I used to test this).

**Comment by wundrweapon** [comment]
> ```
> $ cat /etc/machine-id
> cat: /etc/machine-id: No such file or directory
> $ cat /var/lib/dbus/machine-id
> aaaabbbbccccddddeeeeffff00001111
> $ ls -l ~/.pulse
> ls: cannot access '/home/me/.pulse': No such file or directory
> $ ls -l "${XDG_CONFIG_HOME:-$HOME/.config}"/pulse
> lrwxrwxrwx ... aaaabbbbccccddddeeeeffff00001111-runtime -> /tmp/pulse-AYkIsa0nnIEV
> ... and maybe some other files which I'm not interested in ...
> $ ls -l /tmp/pulse-AYkIsa0nnIEV
> srw-rw-rw- ... native
> -rw------- ... pid
> ```
Yes, this is precisely what I see. That `native` file near the end there has execute permissions as well, but otherwise it's exactly as you expect.  
In case it means anything, PulseAudio is version 14 on my distro/machine.

I'm sorry if repurposing the issue was in poor taste; not only do I understand the importance of keeping such a large project organized, but I know what it's like to get mostly-irrelevant bugmail.

> I consider it polite to lurk for a while and possibly help others when I can

I really like this take. I think I'll apply it to myself, too.

**Comment by smcv** [comment]
This should be fixed in yesterday's beta of Steam Linux Runtime - soldier. The fixes have also been merged back into Flatpak for version 1.10.0.

Switching to the beta branch of `SteamLinuxRuntime_soldier` is the same as switching to the beta branch of a game: please follow the same procedure as https://support.steampowered.com/kb_article.php?ref=9847-WHXC-7326, but in the properties of "Steam Linux Runtime - soldier" rather than CS:GO.

You can check the version numbers of various components by looking at `SteamLinuxRuntime_soldier/VERSIONS.txt`. This particular fix was in pressure-vessel, and for the fixed version you want pressure-vessel 0.20210114.0 or later.

**Comment by 414n** [comment]
Thanks @smcv!
From a first look, the socket seems to be now bind-mounted correctly inside the container:

```sh
$ 2>/tmp/pressure.dbg.log \
  PRESSURE_VESSEL_VERBOSE=1 \
  LC_ALL=en_US \
  /mnt/storage/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point \
    --deploy=soldier \
    --suite=soldier \
    --verb=run  -- \
      bash -c "set | grep ^PULSE; ls -l /run/user/1000/pulse"
PULSE_CLIENTCONFIG=/run/user/1000/pulse/config
PULSE_SERVER=unix:/run/user/1000/pulse/native
total 4
-rw------- 0 alan users 14 Jan 15 13:46 config
srwxrwxrwx 1 alan users  0 Jan 15 09:10 native
```
Here's the pressure vessel log: [pressure.dbg.log.gz](https://github.com/ValveSoftware/steam-runtime/files/5820565/pressure.dbg.log.gz).

This does not seem to fix the issue with "The Witcher 3", however, as the error stays the same: [steam-292030.log.gz](https://github.com/ValveSoftware/steam-runtime/files/5820612/steam-292030.log.gz).
I'm starting to think that there's some other kind of issue between my environment and wine xaudio implementation...

**Comment by smcv** [comment]
> I'm starting to think that there's some other kind of issue between my environment and wine xaudio implementation...

I think so. pressure-vessel seems to be behaving correctly now: it has done the correct bind-mount, and has set `PULSE_SERVER` correctly. `libpulse.so.0` inside the container should be obeying `PULSE_SERVER`, because it's the highest-priority one of the multiple ways it can locate a server.

I don't know why Wine is still selecting ALSA. Maybe because you didn't have working PulseAudio when you first ran it, the fact that it was using the ALSA driver was saved into its configuration?

If you install a different Windows game using Proton, does it play sounds correctly? I often use [Floating Point](https://store.steampowered.com/app/302380/Floating_Point/) for testing, because it's small and will run on anything. It has a native Linux version, but if you select Proton in "Force the use of a specific Steam Play compatibility tool", Steam will install the Windows version instead.

**Comment by 414n** [comment]
> > I'm starting to think that there's some other kind of issue between my environment and wine xaudio implementation...
> 
> I think so. pressure-vessel seems to be behaving correctly now: it has done the correct bind-mount, and has set `PULSE_SERVER` correctly. `libpulse.so.0` inside the container should be obeying `PULSE_SERVER`, because it's the highest-priority one of the multiple ways it can locate a server.

I concur.
 
> I don't know why Wine is still selecting ALSA. Maybe because you didn't have working PulseAudio when you first ran it, the fact that it was using the ALSA driver was saved into its configuration?

Good catch. I tried switching to pulse via winetricks inside that prefix to no avail and also making Proton recreate it from scratch by deleting it first, but that error is still there.
 
> If you install a different Windows game using Proton, does it play sounds correctly? I often use [Floating Point](https://store.steampowered.com/app/302380/Floating_Point/) for testing, because it's small and will run on anything. It has a native Linux version, but if you select Proton in "Force the use of a specific Steam Play compatibility tool", Steam will install the Windows version instead.

I have working sound in almost all Proton titles in my library, except those that make use of xaudio >= 2.7, it seems: for them I need to use a dll override to inhibit the builtin xaudio library. This happens systematically on:
 - The Witcher 3, where I need to choose native xaudio2_7 over builtin for the game to start (`WINEDLLOVERRIDES="xaudio2_7=n,b"`);
 - Killer Instinct, Resident Evil 3 remake and Resident Evil Resistance, where I need to completely disable both xaudio2_8 and xaudio2_7 for the game to start (`WINEDLLOVERRIDES="xaudio2_8,xaudio2_7=d"`), while using Proton-5.21-GE-1.

Meanwhile, other titles like Floating Point and Ultra Street Fighter IV have no issues of this kind and start up just fine, with working audio and all.

**Comment by smcv** [comment]
> Should I open a Proton issue about this?

That sounds like a Proton/Wine issue with xaudio2_7 rather than a problem with the container, so, yes please.

From the pressure-vessel angle, I think our work here is done, unless diagnosis from Proton indicates that there's some more subtle problem with how we make the PA socket available.

**Comment by 414n** [comment]
Ok, I'll open an issue about it soon. :+1: 
Thanks for now

**Comment by wundrweapon** [comment]
I've tested Call of Duty: World at War and DeadCore. This seems to be working!

**Comment by 414n** [comment]
@smcv after some digging, I believe that my xaudio issue (ValveSoftware/Proton#4552) could be another container issue. Could you please take a look at it?

**Comment by kisak-valve** [comment]
Hello @414n, please explain your reasoning on that issue report and I'll transfer it to this issue tracker.

**Comment by 414n** [comment]
Thanks @kisak-valve, much appreciated :+1:

**Comment by smcv** [comment]
> This should be fixed in yesterday's beta of Steam Linux Runtime - soldier [which included] pressure-vessel 0.20210114.0 or later

A suitable version is now included in the default (non-beta) branch.

@kisak-valve, I think we can close this now: the affected users have confirmed that this is working.
