### ISSUE TITLE
Divinity: Original Sin - Enhanced Edition (373420)

### ISSUE THREAD

**Issue by tim77** [ValveSoftware/steam-runtime#359]
# Compatibility Report
- Name of the game with compatibility issues: Divinity: Original Sin - Enhanced Edition
- Steam AppID of the game: 373420

## System Information
- GPU:  GTX 1060 6GB
- Driver/LLVM version:  4.6.0 NVIDIA 460.32.03
- Kernel version:  5.10
- Link to full system information report as [Gist](https://gist.githubusercontent.com/tim77/1448283fe2cda513435c4b345a578f23/raw/c4fabacc013e82205b7e7b4913d56c8f6ea29379/gistfile1.txt).
- Proton version: 5.13-5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-373420.log](https://github.com/ValveSoftware/Proton/files/5895013/steam-373420.log)

## Symptoms 

Game stopped working with Proton 5.13 but used to work with 5.0-10. Game also doesn't work with latest at current date Proton-experimental.

Game can run natively, yes. But in my experience on old AMD CPU i have almost twice FPS with Proton compared to native version. Also there is [well known bug](https://bugs.freedesktop.org/show_bug.cgi?id=93551) when the game won't start on AMD and free Mesa drivers, so Proton could also improve UX for such users.

## Reproduction

1. Just try to launch the game with fresh Proton 5.13-5.
2. Game won't start.

**Comment by kisak-valve** [comment]
Hello @tim77, starting with Proton 5.13, Proton is run inside the Steam Linux Runtime - Soldier container environment and Pressure Vessel is what sets that up. Your system information tells us that lavapipe (mesa's software based vulkan implementation) is getting preferred instead of the video card for 64 bit, and is broken entirely for 32 bit. Let's treat this as a Pressure Vessel issue until there's a stronger indication the issue is elsewhere.

Can you try temporarily disabling lavapipe, MangoHUD, and vkBasalt with something like:
```
sudo mv /usr/share/vulkan/icd.d/lvp_icd.x86_64.json /usr/share/vulkan/icd.d/lvp_icd.x86_64.json.disabled
sudo mv /usr/share/vulkan/icd.d/lvp_icd.i686.json /usr/share/vulkan/icd.d/lvp_icd.i686.json.disabled
sudo mv /usr/share/vulkan/implicit_layer.d/vkBasalt.json /usr/share/vulkan/implicit_layer.d/vkBasalt.json.disabled
sudo mv /usr/share/vulkan/implicit_layer.d/MangoHud.json /usr/share/vulkan/implicit_layer.d/MangoHud.json.disabled
```
and test if that has an effect? If it does, then you can try re-enabling them one at a time by moving them back to their original file names to see if they are relevant or not.

**Comment by tim77** [comment]
@kisak-valve hello and thanks a lot for such a quick and informative respond. I've tried to disable temporary all this stuff but unfortunately still no luck. Here is new log: [steam-373420.log](https://github.com/ValveSoftware/steam-runtime/files/5895411/steam-373420.log)

**Comment by Leopard1907** [comment]
> Also there is well known bug when the game won't start on AMD and free Mesa drivers, so Proton could also improve UX for such users

https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/1841

https://docs.mesa3d.org/relnotes/20.0.0.html

It is fixed last year. Native version works just fine on Mesa now.

**Comment by smcv** [comment]
> Your system information tells us that lavapipe (mesa's software based vulkan implementation) is getting preferred

Actually I'm not so sure that it does tell us that :-(

If you were referring to this message:

```
WARNING: lavapipe is not a conformant vulkan implementation, testing use only
```

In older versions of Mesa, that just meant lavapipe *exists*: it doesn't mean we are actually *using* it. This was fixed in Mesa 20.3.4 (or 20.3.3-1 in Debian) by delaying the warning until the lavapipe device is actually created.

**Comment by tim77** [comment]
So probably it will works on AMD GPU's in fresh Mesa 20.3.4? Can't wait my new AMD video card to replace current nvidia...

**Comment by smcv** [comment]
There seems to be something badly wrong with the 64-bit Vulkan driver, even outside the container:

```
        "x11/vulkan" : {
          "messages" : "... timeout: отслеживаемая команда завершилась созданием дампа\n",
          "renderer" : null,
          "version" : null,
          "issues" : [
            "cannot-load"
          ],
          "exit-status" : -1,
          "terminating-signal" : 11,
          "terminating-signal-name" : "Segmentation fault"
        },
```

I'm guessing "отслеживаемая команда завершилась созданием дампа" is Russian for "segmentation fault".

**Comment by smcv** [comment]
> So probably it will works on AMD GPU's in fresh Mesa 20.3.4?

No idea. The bug that I was referring to as fixed in Mesa 20.3.4 was just "a warning message is printed when it shouldn't be".

**Comment by smcv** [comment]
Inside the container:

```
    "i386-linux-gnu" : {
...
      "graphics-details" : {
        "x11/vulkan" : {
          "messages" : "ERROR: [Loader Message] Code 0 : libVkLayer_MESA_device_select.so: cannot open shared object file: No such file or directory\n ... Vulkan not supported on given X window\n",
          "renderer" : "llvmpipe (LLVM 11.0.0, 256 bits)",
          "version" : "1.0.2 (device 10005:0000) (driver 0.0.1)",
          "issues" : [
            "cannot-draw"
          ],
```

This means: on i386 (i.e. 32-bit), llvmpipe *is* being preferred, for some reason, even though it wasn't when running outside the container. This might be caused by a known bug where we did not load the `libVkLayer_MESA_device_select.so` layer correctly, which is fixed in the beta version of *Steam Linux Runtime - soldier*. The fixed version should go out as the non-beta release later today.

The new version of *Steam Linux Runtime - soldier* will also have some better diagnostic information that should help us to figure out what is happening in situations where the wrong Vulkan driver/GPU is chosen.

**Comment by tim77** [comment]
Tried with today Soldier runtime update.

```
Proton: 1610641627 proton-5.13-5
SteamLinuxRuntime: v0.20210114.1-0-g5a1cbb7
pressure-vessel: 0.20210126.0+srt1 scout 0.20210127.0
soldier: 0.20210126.1 soldier 0.20210126.1
```

Log: [steam-373420.zip](https://github.com/ValveSoftware/steam-runtime/files/5906884/steam-373420.zip)

**Comment by smcv** [comment]
The Proton log is usually not particularly useful for finding runtime bugs. Please could you send updated *Help -> System Information* with the updated runtime? This will list all the GPUs that were found, not just the first one.

The other thing that is most likely to be useful for tracking down runtime bugs is to tell the container runtime to record a log: please see https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md for details.

**Comment by tim77** [comment]
- [steam-sys-info.txt](https://gist.githubusercontent.com/tim77/7b779fdde657cffad92e48f34fb8cac6/raw/47a6c198a5839a9d72b64b3603130caee5560c21/steam-sys-info.txt)
- Steam Linux Runtime log: [slr-app373420-s927ac0582cc000c3.log](https://github.com/ValveSoftware/steam-runtime/files/5917074/slr-app373420-s927ac0582cc000c3.log)

**Comment by RyuzakiKK** [comment]
Now for i386 on Soldier the Nvidia GPU is preferred over the llvmpipe :
```
        "x11/vulkan" : {
          "messages" : [
            [...]
            "{\"device-info\":{\"device-name\":\"GeForce GTX 1060 6GB\",\"device-type\":2,\"api-version\":\"1.2.155\",\"driver-version\":\"460.156.0\",\"vendor-id\":\"0x10de\",\"device-id\":\"0x1c03\"}}",
            "{\"device-info\":{\"device-name\":\"llvmpipe (LLVM 11.0.0, 256 bits)\",\"device-type\":4,\"api-version\":\"1.0.2\",\"driver-version\":\"0.0.1\",\"vendor-id\":\"0x10005\",\"device-id\":\"0\"}}",
            "{\"test\":{\"index\":0,\"can-draw\":true}}",
            "{\"test\":{\"index\":1,\"can-draw\":false,\"error-message\":\"Vulkan not supported on given X window\"}}",
            "Vulkan not supported on given X window"
          ],
          "renderer" : "GeForce GTX 1060 6GB",
          "version" : "1.2.155 (device 10de:1c03) (driver 460.156.0)"
        },
```

But on x86_64 it still fails with a segmentation fault, both on Soldier and also outside the container.

**Comment by smcv** [comment]
> But on x86_64 it still fails with a segmentation fault, both on Soldier and also outside the container

If a simple Vulkan test like that is failing when run outside the container, then that's something you will need to fix before the container will have working Vulkan. We can only try to replicate what is happening outside the container, we cannot fix a driver that doesn't work.

**Comment by artempl** [comment]
Reproducing problem log:
Ubuntu 20.04
AMD Radeon 5500XT
[slr-app373420-sf78a017a48cf943.log](https://github.com/ValveSoftware/steam-runtime/files/5918678/slr-app373420-sf78a017a48cf943.log)

**Comment by smcv** [comment]
@artempl We can't usually tell from just a game log whether you are experiencing the same problem as @tim77, or a different problem that has the same symptoms - particularly if the problem is as general as "it doesn't start".

@tim77 seems to have a non-working 64-bit NVIDIA driver, and you don't seem to be using NVIDIA at all, so I suspect you are seeing something different.

Please could you report a separate issue, with the full system info report, the Steam Linux Runtime log (`slr-app373420-*.log`), and a Proton log (`steam-373420.log`), all from the same situation? See https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md and https://github.com/ValveSoftware/Proton/blob/proton_5.13/.github/ISSUE_TEMPLATE/compatibility-report.md for more information.

It's best if you can include all the information we would ask for in a Steam Runtime issue, *and* all the information the Proton developers would ask for in a Proton issue, because we can't immediately tell whether you are seeing a Steam Runtime bug or a Proton bug.

**Comment by tim77** [comment]
> Please could you report a separate issue, with the full system info report

@smcv hello. Since now i am on Radeon VII but still can't run Divinity: Original Sin - Enhanced Edition via Proton 5.13 i thought that it's fine to post my new logs in this topic. If not, sorry in advance and i'll file in separate topic just tell me.

- [slr-app373420-s43e8e7addb7b31d2.log](https://github.com/ValveSoftware/steam-runtime/files/6095370/slr-app373420-s43e8e7addb7b31d2.log)
- [steam-373420.log](https://github.com/ValveSoftware/steam-runtime/files/6095371/steam-373420.log)
- [steam-sys-amd.txt](https://github.com/ValveSoftware/steam-runtime/files/6095372/steam-sys-amd.txt)

On old Proton 5.0 game works fine on this GPU. Native version also run out of box on this AMD card and can confirm @Leopard1907 [statement](https://github.com/ValveSoftware/steam-runtime/issues/359#issuecomment-770298044).

**Comment by kisak-valve** [comment]
Looking at your updated system information, you could be encountering #363 / #365. Please try running the game with `DISABLE_MANGOHUD=1 %command%` in the game's launch options.

**Comment by tim77** [comment]
@kisak-valve thanks and now with `DISABLE_MANGOHUD=1 %command%` we caught runtime trace: [slr-app373420-s86950d554056c16a.log](https://github.com/ValveSoftware/steam-runtime/files/6095516/slr-app373420-s86950d554056c16a.log)

**Comment by smcv** [comment]
@tim77 Is this game-specific, or a general problem with the container runtime or Proton 5.13?

[Life is Strange](https://store.steampowered.com/app/319630/Life_is_Strange__Episode_1/) (32-bit) and [Life is Strange 2](https://store.steampowered.com/app/532210/Life_is_Strange_2/) (64-bit) are examples of games that are known to work OK under Proton/DXVK in the container. They make good examples because the first episode of each one is free (so anyone can try it), they're not too huge (particularly the first one), they have a native Linux version that you can compare with, and they're single-player (so there's no anti-cheat stuff getting in the way).

Both of the Life is Strange games install a native Linux version by default, but they can be forced to install the Windows version and run it under Proton instead (presumably you're doing the same with D:OS-EE already).

If Life is Strange works fine but D:OS-EE does not, then we might well be better off sending this back to Proton for further debugging by someone who can investigate that specific crash in more detail.

**Comment by tim77** [comment]
> @tim77 Is this game-specific, or a general problem with the container runtime or Proton 5.13?

Quick answer for firs question: i am almost sure this is more like game-specific issue and exception and D:OS the only one game which won't work with new 5.13 Proton. Games which i tested and which works with 5.13: Borderlands 3, Skyrim SE, Everspace and maybe couple more, can't remember right now which exactly.

**Comment by tim77** [comment]
Game works with new Proton 6.3-1. :tada: I've consider this as fixed and a problem was with Proton itself, not runtime. Thanks everyone for looking into this issue.
