### ISSUE TITLE
Steam Linux Runtime doesn't load NVIDIA EGL "external platforms" from host

### ISSUE THREAD

**Issue by smcv** [ValveSoftware/steam-runtime#485]
Recent versions of the NVIDIA proprietary EGL driver `libEGL_nvidia.so.*` have built-in support for X11, but delegate Wayland and GBM support to "external platform" modules. This means that native Wayland games, e.g. with `SDL_VIDEODRIVER=wayland`, won't be accelerated when running on the NVIDIA proprietary driver.

As far as I can tell, X11 games running on Xwayland should be unaffected, regardless of whether they use GLX (common) or EGL (uncommon).

As far as I can tell, Mesa EGL drivers are also unaffected by this.

External platform modules are a new loader/module layer:

```
loader: libEGL from GLVND is a loader for ICDs
    \- module: libEGL_mesa.so.0 from Mesa (via 50_mesa.json)
        \- is a loader for Mesa DRI modules
            \- module: i965_dri.so
            \- module: swrast_dri.so
            \- etc.
    \- module: libEGL_nvidia.so.0 from NVIDIA (via 10_nvidia.json)
        \- is a loader for EGL external platforms
            \- module: libnvidia-egl-wayland.so.1 (via 10_nvidia_wayland.json)
            \- module: libnvidia-egl-gbm.so.1 (via 15_nvidia_gbm.json)
```

The spec at https://github.com/NVIDIA/eglexternalplatform unfortunately doesn't describe how to find them, and the code in libEGL_nvidia.so.0 is proprietary, but it looks as though it follows a pattern similar to how EGL ICDs are discovered: search `/etc/egl/egl_external_platform.d:/usr/share/egl/egl_external_platform.d` or `$__EGL_EXTERNAL_PLATFORM_CONFIG_FILENAMES` or `$__EGL_EXTERNAL_PLATFORM_CONFIG_DIRS` for `.json` manifests in the same format as EGL ICDs' manifests, and load them all.

We should teach `pressure-vessel-wrap` to enumerate these modules, load their JSON manifests, rewrite the paths mentioned in the manifests if necessary, and map them into the container for use by native Wayland games. I expect this will mostly consist of repurposing the code we already have for EGL ICDs.

We should also teach the `steam-runtime-system-info` diagnostic tool to list them, the same way it can already list EGL ICDs and Mesa DRI modules.

**Comment by smcv** [comment]
https://github.com/NVIDIA/egl-wayland is open source and might be a useful reference, but we should probably take the known-good version from the host instead of compiling our own.

**Comment by smcv** [comment]
> The spec at https://github.com/NVIDIA/eglexternalplatform unfortunately doesn't describe how to find them

https://github.com/NVIDIA/eglexternalplatform/issues/3 asks for a spec or reference implementation for how it works.

**Comment by smcv** [comment]
Fixed in https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/merge_requests/411, which will hopefully be in the next beta of `SteamLinuxRuntime_soldier`.

**Comment by smcv** [comment]
This change has gone out in `SteamLinuxRuntime_soldier` build [0.20220120.41](https://gitlab.steamos.cloud/steamrt/steamrt/-/wikis/Soldier-release-notes#soldier-depot-02022012041-steampipe-build-id-8051642), which is currently on the `client_beta` branch of `SteamLinuxRuntime_soldier` (you can [opt in](https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#using-a-beta-or-an-older-version) to using this beta, it is not used by default). If you have the fixed version, you will see `pressure-vessel 0.20220119.0` or later in `SteamLinuxRuntime_soldier/VERSIONS.txt`.

It is likely to be "promoted" into the stable releases that are used by default at some point in the future.

**Comment by smcv** [comment]
> It is likely to be "promoted" into the stable releases that are used by default at some point in the future.

This has now happened.

**Comment by OverFlow92** [comment]
Still reproducible in 2026 (Steam Runtime "steamrt3c" / pressure-vessel bundled with Steam 1.0.0.85, driver 580.126.09) — but only for the GBM external platform, not Wayland. The 2022 fix in !411 appears to have only added capture for libnvidia-egl-wayland.so.1's manifest; 15_nvidia_gbm.json under egl_external_platform.d is never captured, and 10_nvidia.json under glvnd/egl_vendor.d is intermittently missed when the host stores it as a symlink (e.g. into /var/run/nvidia/configs/, as some read-only-root distros like Batocera do).

Full diagnostic + a separate but possibly related black-screen bug: ValveSoftware/steam-for-linux#13519

**Comment by smcv** [comment]
> Still reproducible in 2026

Please open a separate issue with full details (steps to reproduce / expected result / actual result) in preference to commenting on an issue that was closed in 2022. It is likely that something has changed between 2022 and now.

See https://github.com/ValveSoftware/steam-for-linux/issues/13519#issuecomment-5317988545 for information that will be needed.
